FROM nginx:1.23.3
COPY ./dist/social-network-frontend/* /usr/share/nginx/html
EXPOSE 80

#docker login -u alejandrotrilla
#docker build -t alejandrotrilla/social-network-frontend .
#docker push alejandrotrilla/social-network-frontend
